# Generated by Django 5.0.6 on 2024-06-24 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home_electricity_consumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('global_active_power', models.FloatField(default=0)),
                ('global_reactive_power', models.FloatField(default=0)),
                ('voltage', models.FloatField(default=0)),
                ('global_intensity', models.FloatField(default=0)),
                ('sub_metering_1', models.FloatField(default=0)),
                ('sub_metering_2', models.FloatField(default=0)),
                ('sub_metering_3', models.FloatField(default=0)),
            ],
        ),
    ]
