# Generated by Django 5.0.6 on 2024-06-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home_electricity_consumption',
            name='time',
        ),
        migrations.AlterField(
            model_name='home_electricity_consumption',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
