# Generated by Django 5.0.6 on 2024-06-28 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_home', '0002_remove_home_electricity_consumption_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home_electricity_consumption',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
