# Generated by Django 5.0.6 on 2024-06-29 21:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_home', '0005_alter_home_electricity_consumption_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home_electricity_consumption',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 30, 0, 59, 53, 480980)),
        ),
    ]
